package com.cisco.sitemgmt.siteselfassessment;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class FindingMitigationplan implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "FINDINGMITIGATIONPLAN_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(name = "FINDINGMITIGATIONPLAN_ID_GENERATOR", sequenceName = "FINDINGMITIGATIONPLAN_ID_SEQ")
    private java.lang.Long id;

    public FindingMitigationplan() {
    }
    
    public FindingMitigationplan(java.lang.Long id) {
        this.id = id;
    }

    public java.lang.Long getId() {
        return this.id;
    }
    
    public void setId(java.lang.Long id) {
        this.id = id;
    }

}